inputs:
  version-suffix:
    description: 'The suffix for the next version'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Bump version
      run: ${{ github.action_path }}/bump-version.sh ${{ inputs.build-tool }} ${{ inputs.version-suffix }}
      shell: bash