runs:
  using: "composite"
  steps: 
    - name: Get version
      run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "MVN_VERSION=$VERSION" >> $GITHUB_ENV
      shell: bash

    - name: Get artifactId
      run: |
          ARTIFACT=$( mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout )
          echo "MVN_ARTIFACT=$ARTIFACT" >> $GITHUB_ENV
      shell: bash

    - name: Get groupId
      run: |
          GROUP=$( mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout )
          echo "MVN_GROUP=$GROUP" >> $GITHUB_ENV
      shell: bash