# This workflow does all the tagging, building, publishing etc. around a new release

name: release

on:
  push:
    branches:
    - main

env:
  DOCKERHUB_USERNAME: lukecmstevens

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    # Finalise the version by removing the -beta or -SNAPSHOT suffix if it exists

    - name: Finalise version
      uses: lukecmstevens/actions/finalise-version@v1

    # Get project properties and store in environment

    - name: Get properties
      uses: lukecmstevens/actions/get-project-properties@v1

    # Setup for docker build and push

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Push docker artifact to repo
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true # Don't push until certain it works
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:latest
        build-args: |
          NAME=${{ env.PROJECT_NAME }}
          VERSION=${{ env.PROJECT_VERSION }}

    # We finalised the version earlier, now committing, tagging, and pushing to main

    - name: Commit and tag version update
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        commit_message: Release version ${{ env.PROJECT_VERSION }}
        tagging_message: ${{ env.PROJECT_VERSION }}

    # Create a release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.PROJECT_VERSION }}
        release_name: Release ${{ env.PROJECT_VERSION }}
        body_path: changelog.md

    # Switch to develop, bump version and commit

    - name: Switch to develop
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Bump version
      uses: lukecmstevens/actions/bump-version@v1
      with:
        version-suffix: beta

    - name: Commit and push bumped version
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: develop
        commit_message: Bump version

        
